package examples.codegen.javaInterop;
public class main{
    public static plaid.fastruntime.PlaidObject invoke$plaid() {
        plaid.fastruntime.PlaidObject vaR0$plaid;
        plaid.fastruntime.PlaidObject vaR1$plaid;
        plaid.fastruntime.PlaidState vaR2$plaid;
        vaR2$plaid = plaid.lang.True.theState$plaid;
        vaR1$plaid = vaR2$plaid.instantiate();
        final plaid.fastruntime.PlaidObject t = vaR1$plaid;
        plaid.fastruntime.PlaidObject vaR3$plaid;
        plaid.fastruntime.PlaidState vaR4$plaid;
        vaR4$plaid = plaid.lang.False.theState$plaid;
        vaR3$plaid = vaR4$plaid.instantiate();
        final plaid.fastruntime.PlaidObject f = vaR3$plaid;
        plaid.fastruntime.PlaidObject vaR5$plaid;
        plaid.fastruntime.PlaidObject vaR6$plaid;
        vaR6$plaid = t;
        plaid.fastruntime.PlaidObject vaR7$plaid;
        vaR7$plaid = f;
        vaR5$plaid = ((plaid.generated.Iampamp$plaid$1$plaid)vaR6$plaid.getDispatch()).ampamp$plaid(vaR6$plaid,vaR7$plaid);
        final plaid.fastruntime.PlaidObject b = vaR5$plaid;
        plaid.fastruntime.PlaidObject vaR8$plaid;
        plaid.fastruntime.PlaidObject vaR9$plaid;
        vaR9$plaid = b;
        vaR8$plaid = ((plaid.generated.ItoString$0$plaid)vaR9$plaid.getDispatch()).toString(vaR9$plaid);
        plaid.fastruntime.PlaidObject vaR10$plaid;
        vaR10$plaid = plaid.fastruntime.Util.JAVA_GEN.createPlaidJavaObject(java.lang.System.out);
        vaR0$plaid = ((plaid.generated.Iprintln$1$plaid)vaR10$plaid.getDispatch()).println(vaR10$plaid,vaR8$plaid);
        plaid.fastruntime.PlaidObject vaR11$plaid;
        vaR11$plaid = plaid.fastruntime.Util.integer(5);
        final plaid.fastruntime.PlaidObject n = vaR11$plaid;
        plaid.fastruntime.PlaidObject vaR12$plaid;
        vaR12$plaid = plaid.fastruntime.Util.integer(6);
        final plaid.fastruntime.PlaidObject m = vaR12$plaid;
        plaid.fastruntime.PlaidObject vaR13$plaid;
        plaid.fastruntime.PlaidObject vaR14$plaid;
        vaR14$plaid = m;
        plaid.fastruntime.PlaidObject vaR15$plaid;
        vaR15$plaid = n;
        vaR13$plaid = ((plaid.generated.Iplus$plaid$1$plaid)vaR14$plaid.getDispatch()).plus$plaid(vaR14$plaid,vaR15$plaid);
        final plaid.fastruntime.PlaidObject p = vaR13$plaid;
        plaid.fastruntime.PlaidObject vaR16$plaid;
        plaid.fastruntime.PlaidObject vaR17$plaid;
        vaR17$plaid = p;
        vaR16$plaid = ((plaid.generated.ItoString$0$plaid)vaR17$plaid.getDispatch()).toString(vaR17$plaid);
        plaid.fastruntime.PlaidObject vaR18$plaid;
        vaR18$plaid = plaid.fastruntime.Util.JAVA_GEN.createPlaidJavaObject(java.lang.System.out);
        vaR0$plaid = ((plaid.generated.Iprintln$1$plaid)vaR18$plaid.getDispatch()).println(vaR18$plaid,vaR16$plaid);
        plaid.fastruntime.PlaidObject vaR19$plaid;
        vaR19$plaid = plaid.fastruntime.Util.string("this is a string");
        final plaid.fastruntime.PlaidObject s = vaR19$plaid;
        plaid.fastruntime.PlaidObject vaR20$plaid;
        plaid.fastruntime.PlaidObject vaR21$plaid;
        plaid.fastruntime.PlaidObject vaR22$plaid;
        plaid.fastruntime.PlaidObject vaR23$plaid;
        plaid.fastruntime.PlaidObject vaR24$plaid;
        vaR23$plaid = plaid.fastruntime.Util.integer(0);
        vaR24$plaid = plaid.fastruntime.Util.integer(10);
        plaid.fastruntime.PlaidObject vaR25$plaid;
        vaR25$plaid = s;
        vaR22$plaid = ((plaid.generated.Isubstring$2$plaid)vaR25$plaid.getDispatch()).substring(vaR25$plaid,vaR23$plaid,vaR24$plaid);
        plaid.fastruntime.PlaidObject vaR26$plaid;
        vaR26$plaid = plaid.fastruntime.Util.string("plaid ");
        vaR21$plaid = ((plaid.generated.Iplus$plaid$1$plaid)vaR22$plaid.getDispatch()).plus$plaid(vaR22$plaid,vaR26$plaid);
        plaid.fastruntime.PlaidObject vaR27$plaid;
        plaid.fastruntime.PlaidObject vaR28$plaid;
        plaid.fastruntime.PlaidObject vaR29$plaid;
        vaR28$plaid = plaid.fastruntime.Util.integer(10);
        plaid.fastruntime.PlaidObject vaR30$plaid;
        vaR30$plaid = s;
        vaR29$plaid = ((plaid.generated.Ilength$0$plaid)vaR30$plaid.getDispatch()).length(vaR30$plaid);
        plaid.fastruntime.PlaidObject vaR31$plaid;
        vaR31$plaid = s;
        vaR27$plaid = ((plaid.generated.Isubstring$2$plaid)vaR31$plaid.getDispatch()).substring(vaR31$plaid,vaR28$plaid,vaR29$plaid);
        vaR20$plaid = ((plaid.generated.Iplus$plaid$1$plaid)vaR21$plaid.getDispatch()).plus$plaid(vaR21$plaid,vaR27$plaid);
        final plaid.fastruntime.PlaidObject u = vaR20$plaid;
        plaid.fastruntime.PlaidObject vaR32$plaid;
        vaR32$plaid = u;
        plaid.fastruntime.PlaidObject vaR33$plaid;
        vaR33$plaid = plaid.fastruntime.Util.JAVA_GEN.createPlaidJavaObject(java.lang.System.out);
        vaR0$plaid = ((plaid.generated.Iprintln$1$plaid)vaR33$plaid.getDispatch()).println(vaR33$plaid,vaR32$plaid);
        return vaR0$plaid;
    }
    public static void main(String[] args) {
        invoke$plaid();
    }
}
